export const types = {
  GET_LIST_USER: 'GET_LIST_USER',
  GET_DETAIL_USER: 'GET_DETAIL_USER',

  UPDATE_DETAIL_USER: 'UPDATE_DETAIL_USER',
  UPDATE_LIST_USER: 'UPDATE_LIST_USER',
  UPDATE_LIST_USER_RESET: 'UPDATE_LIST_USER_RESET',

  GET_LOGIN: 'GET_LOGIN',
  INSERT_USER: 'INSERT_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  USER_SUCCESS: 'USER_SUCCESS',
  USER_FAILURE: 'USER_FAILURE',
  USER_RESET: 'USER_RESET',

  GET_CONTACT: 'GET_CONTACT',
  GET_CONTACTS: 'GET_CONTACTS',

  INSERT_CONTACT: 'INSERT_CONTACT',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',

  FETCH_CONTACT_SUCCESS: 'FETCH_CONTACT_SUCCESS',
  CONTACT_SUCCESS: 'CONTACT_SUCCESS',
  CONTACT_FAILURE: 'CONTACT_FAILURE',
  CONTACT_RESET: 'CONTACT_RESET',
};
