import {StyleSheet} from 'react-native';

const color = {
  tblack: '#404040',
  tblack2: '#1f1f1f',
  tgrey: '#BFBFBF',
  tgrey2: '#F3F4F8',
  tgrey3: '#C7C9D9',
  line: '#DDE5E9',
  blue: '#14539a',
  blue2: '#097bed',
  blue3: '#e0f7fa',
  blue4: '#e4effb',
  blue5: '#3670b2',
  blue6: '#255e9f',
  blue7: '#4599DB',
  bluept: '#0d4b74d8',
  bluep: '#0D4B74',
  bluep1: '#2E688E',
  bluep2: '#4F85A8',
  bluep3: '#70A1C2',
  bluep4: '#91BEDC',
  bluep5: '#6E5DE7',
  bluep6: '#eeecfe',
  bluep7: '#a69bf9',
  bluep8: '#9b59b6',
  grey: '#bbb',
  grey2: '#666',
  grey3: '#7a7a7a',
  grey4: '#34495e',
  grey5: '#545454',
  white: '#fff',
  white2: '#f2f2f2',
  white3: '#e9e9e9',
  white4: '#f4f8fb',
  white5: 'rgba(255, 255, 255, 0.5)',
  white6: '#ffffff3d',
  white7: '#F6F9FF',
  white8: '#F9F9F9',
  white9: '#f5f5f5',
  white10: '#f6f6f6',
  red: '#da1414',
  red2: '#ff2d55',
  red3: '#ffeef2',
  orange: '#ff9500',
  orange2: '#fff6e7',
  oranges: '#F0C312',
  oranges1: '#F3CF41',
  oranges2: '#F6DB71',
  oranges3: '#F9E7A0',
  oranges4: '#FCF3D0',
  oranget: '#F09D07',
  oranget1: '#F3B139',
  oranget2: '#F6C46A',
  oranget3: '#F9D89C',
  oranget4: '#FCEBCD',
  green: '#1ABC9C',
  green2: '#def0db',
  green3: '#019f4a',
  green4: '#58b4b5',
  green9: '#58b4b4',
  green5: '#eef7f9',
  green7: '#e6eda7',
  green8: '#f6f8dc',
  green10: '#253737e6',
  green11: '#62CDCB',
  loading: '#00000060',
  background: '#FFFFFF0F',
  background1: '#1F4247',
  background2: '#0D1D23',
  background3: '#09141A',
  background4: '#162329',
  background5: '#0E191F',
};

const styles = StyleSheet.create({
  textBlack: {fontFamily: 'Poppins-Black'},
  textBlackItalic: {fontFamily: 'Poppins-BlackItalic'},
  textBold: {fontFamily: 'Poppins-Bold'},
  textBoldItalic: {fontFamily: 'Poppins-BoldItalic'},
  textExtraBold: {fontFamily: 'Poppins-ExtraBold'},
  textExtraBoldItalic: {fontFamily: 'Poppins-ExtraBoldItalic'},
  textExtraLight: {fontFamily: 'Poppins-ExtraLight'},
  textExtraLightItalic: {fontFamily: 'Poppins-ExtraLightItalic'},
  textItalic: {fontFamily: 'Poppins-Italic'},
  textLight: {fontFamily: 'Poppins-Light'},
  textLightItalic: {fontFamily: 'Poppins-LightItalic'},
  textMedium: {fontFamily: 'Poppins-Medium'},
  textMediumItalic: {fontFamily: 'Poppins-MediumItalic'},
  textRegular: {fontFamily: 'Poppins-Regular'},
  textSemiBold: {fontFamily: 'Poppins-SemiBold'},
  textSemiBoldItalic: {fontFamily: 'Poppins-SemiBoldItalic'},
  textThin: {fontFamily: 'Poppins-Thin'},
  textThinItalic: {fontFamily: 'Poppins-ThinItalic'},
  textDefault: (
    size = 12,
    clr = color.white,
    type = 'textRegular',
    transform = 'none',
  ) => [
    styles[type],
    {
      paddingTop: 4,
      fontSize: size,
      color: clr,
      textTransform: transform,
    },
  ],
  textBase: (
    size = 13,
    clr = color.white,
    type = 'textMedium',
    transform = 'capitalize',
  ) => [
    styles[type],
    {
      paddingTop: 4,
      fontSize: size,
      color: clr,
      textTransform: transform,
      lineHeight: size,
    },
  ],
  h1: (clr, align = 'left', fontStyle = 'textSemiBold') => [
    styles.textBase(30, clr, fontStyle),
    {textAlign: align},
  ],
  h2: (clr, align = 'left', fontStyle = 'textSemiBold') => [
    styles.textBase(24, clr, fontStyle),
    {textAlign: align},
  ],
  h3: (clr, align = 'left', fontStyle = 'textSemiBold') => [
    styles.textBase(18, clr, fontStyle),
    {textAlign: align},
  ],
  h4: (clr, align = 'left', fontStyle = 'textSemiBold') => [
    styles.textBase(16, clr, fontStyle),
    {textAlign: align},
  ],
  h5: (clr, align = 'left', fontStyle = 'textSemiBold') => [
    styles.textBase(14, clr, fontStyle),
    {textAlign: align},
  ],
  h6: (clr, align = 'left', fontStyle = 'textRegular') => [
    styles.textBase(14, clr, fontStyle),
    {textAlign: align},
  ],
  h7: (clr, align = 'left', fontStyle = 'textSemiBold') => [
    styles.textBase(12, clr, fontStyle),
    {textAlign: align},
  ],
  h8: (clr, align = 'left', fontStyle = 'textSemiBold') => [
    styles.textBase(10, clr, fontStyle),
    {textAlign: align},
  ],
  h9: (clr, align = 'left', fontStyle = 'textRegular') => [
    styles.textBase(10, clr, fontStyle),
    {textAlign: align},
  ],
  p1: (clr, align = 'left', fontStyle = 'textRegular') => [
    styles.textBase(16, clr, fontStyle),
    {textAlign: align},
  ],
  p2: (clr, align = 'left', fontStyle = 'textMedium') => [
    styles.textBase(14, clr, fontStyle),
    {textAlign: align},
  ],
  p3: (clr, align = 'left', fontStyle = 'textRegular') => [
    styles.textBase(14, clr, fontStyle),
    {textAlign: align},
  ],
  p4: (clr, align = 'left', fontStyle = 'textRegular') => [
    styles.textBase(12, clr, fontStyle),
    {textAlign: align},
  ],
  p5: (clr, align = 'left', fontStyle = 'textMedium') => [
    styles.textBase(11, clr, fontStyle),
    {textAlign: align},
  ],
  p6: (clr, align = 'left', fontStyle = 'textMedium') => [
    styles.textBase(8, clr, fontStyle),
    {textAlign: align},
  ],
  p7: (clr, align = 'left', fontStyle = 'textRegular') => [
    styles.textBase(8, clr, fontStyle),
    {textAlign: align},
  ],
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  shadowCust: (
    elevation = 6,
    shadowRadius = 5,
    shadowOpacity = 0.1,
    height = 5,
    width = 0,
    shadowColor = color.tblack,
  ) => ({
    shadowColor: shadowColor,
    shadowOffset: {
      width: width,
      height: height,
    },
    shadowOpacity: shadowOpacity,
    shadowRadius: shadowRadius,
    elevation: elevation,
  }),
});

export {styles, color};
